version: '3.8'

services:
  # Flask backend API
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: backend-service
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db

  # Static frontend served by NGINX
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    container_name: frontend-service
    ports:
      - "3000:80"
    depends_on:
      - backend

  # MySQL database service
  db:
    image: mysql:8
    container_name: mysql-db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}

# Volume to persist database data
volumes:
  db_data:
